openapi: 3.0.3
info:
  title: Task Management API
  description: API for managing tasks with CRUD operations
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server

paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieve a list of all tasks
      operationId: getTasks
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a new task
      description: Create a new task with the provided details
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{id}:
    get:
      summary: Get a task by ID
      description: Retrieve a single task by its ID
      operationId: getTaskById
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the task to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a task
      description: Update an existing task by its ID
      operationId: updateTask
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a task
      description: Delete an existing task by its ID
      operationId: deleteTask
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the task to delete
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - description
        - duration
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the task
          example: 1
        title:
          type: string
          description: Title of the task
          example: "Complete project documentation"
        description:
          type: string
          description: Detailed description of the task
          example: "Write comprehensive documentation for the API endpoints"
        duration:
          type: integer
          description: Duration of the task in minutes
          example: 120

    TaskInput:
      type: object
      required:
        - title
        - description
        - duration
      properties:
        title:
          type: string
          description: Title of the task
          example: "Complete project documentation"
        description:
          type: string
          description: Detailed description of the task
          example: "Write comprehensive documentation for the API endpoints"
        duration:
          type: integer
          description: Duration of the task in minutes
          minimum: 1
          example: 120

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: "An error occurred"
        code:
          type: string
          description: Error code
          example: "INTERNAL_ERROR"
