openapi: 3.0.3
info:
  title: Task Management API
  description: A RESTful API for managing tasks with CRUD operations
  version: 1.0.0
  contact:
    name: Task Management Team
    email: support@taskmanagement.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://api.taskmanagement.com/v1
    description: Production server

paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieve a list of all tasks
      operationId: getTasks
      parameters:
        - name: limit
          in: query
          description: Maximum number of tasks to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of tasks to skip for pagination
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  total:
                    type: integer
                    description: Total number of tasks
                  limit:
                    type: integer
                    description: Maximum number of tasks returned
                  offset:
                    type: integer
                    description: Number of tasks skipped
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      summary: Create a new task
      description: Create a new task with the provided information
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{id}:
    get:
      summary: Get a task by ID
      description: Retrieve a specific task by its ID
      operationId: getTaskById
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the task to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a task
      description: Update an existing task with new information
      operationId: updateTask
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a task
      description: Delete a specific task by its ID
      operationId: deleteTask
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the task to delete
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health:
    get:
      summary: Health check
      description: Check the health status of the service
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                  version:
                    type: string
                    example: "1.0.0"

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - description
        - duration
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the task
          example: 1
        title:
          type: string
          maxLength: 255
          description: The title of the task
          example: "Complete project documentation"
        description:
          type: string
          maxLength: 1000
          description: Detailed description of the task
          example: "Write comprehensive documentation for the task management API"
        duration:
          type: integer
          minimum: 1
          description: Estimated duration in minutes
          example: 120
        created_at:
          type: string
          format: date-time
          description: When the task was created
          example: "2023-12-04T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: When the task was last updated
          example: "2023-12-04T10:30:00Z"

    CreateTaskRequest:
      type: object
      required:
        - title
        - description
        - duration
      properties:
        title:
          type: string
          maxLength: 255
          description: The title of the task
          example: "Complete project documentation"
        description:
          type: string
          maxLength: 1000
          description: Detailed description of the task
          example: "Write comprehensive documentation for the task management API"
        duration:
          type: integer
          minimum: 1
          description: Estimated duration in minutes
          example: 120

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
          description: The title of the task
          example: "Complete project documentation"
        description:
          type: string
          maxLength: 1000
          description: Detailed description of the task
          example: "Write comprehensive documentation for the task management API"
        duration:
          type: integer
          minimum: 1
          description: Estimated duration in minutes
          example: 120

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Error code
          example: 400
        message:
          type: string
          description: Error message
          example: "Invalid request parameters"
        details:
          type: string
          description: Additional error details
          example: "The 'title' field is required and cannot be empty"